# Generated by Django 4.0.4 on 2022-06-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backup',
            old_name='uploadedFile',
            new_name='archivo',
        ),
        migrations.RenameField(
            model_name='backup',
            old_name='dateTimeOfUpload',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='backup',
            old_name='title',
            new_name='nombre',
        ),
    ]
