# Generated by Django 4.0.4 on 2022-05-23 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallefondo',
            options={'verbose_name': 'Detalle Fondo', 'verbose_name_plural': 'contabilidad.DetalleFondo'},
        ),
        migrations.AlterModelOptions(
            name='fondo',
            options={'verbose_name': 'Fondo', 'verbose_name_plural': 'contabilidad.Fondo'},
        ),
        migrations.AlterModelOptions(
            name='tapa',
            options={'verbose_name': 'Tapa', 'verbose_name_plural': 'contabilidad.Tapa'},
        ),
    ]
