# Generated by Django 4.0.3 on 2022-04-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallefondo',
            old_name='equipo_id',
            new_name='equipo',
        ),
        migrations.RenameField(
            model_name='detallefondo',
            old_name='fondo_id',
            new_name='fondo',
        ),
        migrations.RenameField(
            model_name='tapa',
            old_name='aprendiz_id',
            new_name='aprendiz',
        ),
    ]
