# Generated by Django 4.0.4 on 2022-05-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aprendiz',
            options={'verbose_name': 'Aprendiz', 'verbose_name_plural': 'personal.Aprendiz'},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'verbose_name': 'Equipo', 'verbose_name_plural': 'personal.Equipo'},
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='activo',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Activo'),
        ),
    ]
