# Generated by Django 4.0.3 on 2022-04-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aprendiz',
            old_name='equipo_id',
            new_name='equipo',
        ),
    ]
