# Generated by Django 4.0.4 on 2022-05-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_aprendiz_options_alter_equipo_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aprendiz',
            old_name='activo',
            new_name='estado',
        ),
    ]
