# Generated by Django 4.0.3 on 2022-04-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_alter_equipo_puntos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='puntos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
