# Generated by Django 4.0.4 on 2022-04-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_alter_equipo_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendiz',
            name='activo',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default=('1', 'Activo'), max_length=1, verbose_name='Activo'),
        ),
    ]
