# Generated by Django 4.0.4 on 2022-04-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_aprendiz_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='activo',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Activo'),
        ),
    ]
